### ISSUE TITLE
2015 support?

### ISSUE THREAD

**Issue by mooreniemi** [kriasoft/fsharp-starter-kit#2]
> This package is reporting a dependency for Nuget Package Manager for Visual Studio 2013 when attempting to install it through Extensions and Updates in Visual Studio 2015.

As reported on https://visualstudiogallery.msdn.microsoft.com/c7ea6e81-b383-40e4-899c-4a5ab9d68f02

I'm also experiencing.

**Comment by koistya** [comment]
@mooreniemi thanks for the report! Sorry, I haven't responded to this issue earlier. FYI, I just refactored this project template to support .NET Core and cross-platform development. You can restore NuGet packages by running `dotnet restore`.
