### ISSUE TITLE
Unable to resolve netcore

### ISSUE THREAD

**Issue by rodrigovidal** [kriasoft/fsharp-starter-kit#3]
Hi, I'm following the instructions in readme but I'm getting these errors. 

Do you any ideas?

  Unable to resolve 'Microsoft.FSharp.Core.netcore (>= 1.0.0-alpha-160509)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.FSharp.Compiler.netcore (>= 1.0.0-alpha-160318)' for '.NETCoreApp,Version=v1.0'.

Thank you.

**Comment by rodrigovidal** [comment]
I've fixed it. Maybe you could add in readme to run "dotnet restore" from the server folder. Thanks.

**Comment by koistya** [comment]
Hm, interesting.. perhaps a bug in dotnet cli. Thanks for the hint.

**Comment by koistya** [comment]
@rodrigovidal can you check please if 9a6dc34 fixed the issue? Also, I just pushed an update to the front-end app and build scripts in 33b982394b144501824071f9207603dc9edb0fc3. More stuff is coming soon.
